### ISSUE TITLE
Response error from Django server

### ISSUE THREAD

**Issue by dedmari** [ZachLiuGIS/reactjs-auth-django-rest#1]
I am trying to run the application and i am getting this error "Error logging in XMLHttpRequest { onreadystatechange: [310]</</noop(), readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:8000/rest-auth/reg…", status: 500, statusText: "INTERNAL SERVER ERROR", responseType: "", response: "AttributeError at /rest-auth/registration/
can't set attribute". It occurs during registering new user.

**Comment by ZachLiuGIS** [comment]
Sorry for the late reply, what django-allauth version did you use?
